namespace Lib.CppWinRT
{
    [default_interface]
    runtimeclass MyStruct
    {
        MyStruct();
        Double Add(Double x, Double y);
        Double Subtract(Double x, Double y);
        Double Multiply(Double x, Double y);
        Double Divide(Double x, Double y);
    }
}
